service: house-bot
frameworkVersion: "2"

provider:
  name: aws
  runtime: nodejs12.x
  lambdaHashingVersion: 20201221
  region: ap-southeast-1

functions:
  remind:
    handler: handler.remind
    events:
      - httpApi:
          path: /remind
          method: get
      - schedule: cron(0 13 ? * 6 *) # every mon, wed, fri, sun
